package vista;

import java.awt.event.ActionListener;
import java.sql.Date;
import java.util.Calendar;

import javax.swing.JOptionPane;

import implementacion.ClienteDao;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rauls
 */
public class VistaCliente extends javax.swing.JFrame {

	/**
	 * Creates new form VistaEmpleado
	 */
	public VistaCliente() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		mesBox = new javax.swing.JComboBox();
		diaSpinner = new javax.swing.JSpinner();
		anioSpinner = new javax.swing.JSpinner();
		nombreText = new javax.swing.JTextField();
		apellido1Text = new javax.swing.JTextField();
		apellido2Text = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		telefonoText = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		dniText = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		emailText = new javax.swing.JTextField();
		aniadirButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel3.setText("Nombre");

		jLabel4.setText("Apelliido 1");

		mesBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril",
				"Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

		jLabel5.setText("Apellido 2");

		jLabel6.setText("Fecha Nacimiento");

		jLabel7.setText("Telefono");

		jLabel8.setText("DNI");

		jLabel9.setText("Email");

		aniadirButton.setText("Agregar");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addGap(22, 22, 22)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(apellido2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 141,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(apellido1Text, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 141,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(nombreText, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 141,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32,
										Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(emailText, javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(dniText, javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(telefonoText, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 149,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(38, 38, 38))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(diaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(mesBox, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(anioSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 70,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(90, 90, 90))
				.addGroup(layout.createSequentialGroup().addGap(202, 202, 202).addComponent(aniadirButton)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(25, 25, 25)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(16, 16, 16)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 15,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(apellido1Text, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(apellido2Text, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel5)))
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel8)
								.addComponent(telefonoText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(16, 16, 16)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel9).addComponent(dniText,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel7))))
				.addGap(29, 29, 29)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(mesBox, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(diaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(anioSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel6))
				.addGap(18, 18, 18).addComponent(aniadirButton)
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	public void listenerAniadirButton(ActionListener listenerForButtons) {
		this.aniadirButton.setText("Añadir");
		this.aniadirButton.addActionListener(listenerForButtons);
	}
	
	public void listenerModificarButton(ActionListener listenerForButtons) {
		this.aniadirButton.setText("Modificar");
		this.aniadirButton.addActionListener(listenerForButtons);
	}

	public void avisarClienteAniadidoCorrecto() {
		JOptionPane.showMessageDialog(null, "Cliente añadido correctamente", null, JOptionPane.INFORMATION_MESSAGE,
				null);
	}
	
	public void avisarClienteModificadoCorrecto() {
		JOptionPane.showMessageDialog(null, "Cliente modificado correctamente", null, JOptionPane.INFORMATION_MESSAGE,
				null);
	}

	public String mostrarVentanaBajaCliente() {
		String dni = JOptionPane.showInputDialog(null, "Introduce el DNI:", "Baja Cliente",
				JOptionPane.QUESTION_MESSAGE);
		return dni;
	}
	
	public String mostrarVentanaConsultarCliente() {
		String dni = JOptionPane.showInputDialog(null, "Introduce el DNI:", "Consultar Cliente",
				JOptionPane.QUESTION_MESSAGE);
		return dni;
	}

	public String getDNIText() {
		return dniText.getText();
	}

	public String getNombreText() {
		return nombreText.getText();
	}

	public String getApellidosText() {
		return apellido1Text.getText() + " " + apellido2Text.getText();
	}

	public String getTelefonoText() {
		return telefonoText.getText();
	}

	public String getEmailText() {
		return emailText.getText();
	}

	public Date getNacimientoDate() {
		Calendar cal = Calendar.getInstance();
		cal.set(Calendar.YEAR, Integer.valueOf(anioSpinner.getValue().toString()));
		cal.set(Calendar.MONTH, mesBox.getSelectedIndex());
		cal.set(Calendar.DAY_OF_MONTH, Integer.valueOf(diaSpinner.getValue().toString()));
		return new Date(cal.getTimeInMillis());
	}

	public void setApellidosText(String apellidos) {
		String[] apellidosSplit = apellidos.split(" ");
		this.apellido1Text.setText(apellidosSplit[0]);
		this.apellido2Text.setText(apellidosSplit[1]);
	}

	public void setNombreText(String nombre) {
    	this.nombreText.setText(nombre);
    }

	public void setTelefonoText(String telefono) {
    	this.telefonoText.setText(telefono);
    }

	public void setDNIText(String dni) {
    	this.dniText.setText(dni);
    }

	public void setEmailText(String email) {
    	this.emailText.setText(email);
    }

	public void setNacimientoDate(Date fecha) {
		Calendar cal = Calendar.getInstance();
		cal.setTime(fecha);
		this.diaSpinner.setValue(cal.get(Calendar.DAY_OF_MONTH));
		this.mesBox.setSelectedIndex(cal.get(Calendar.MONTH));
		this.anioSpinner.setValue(cal.get(Calendar.YEAR));
	}

	// Variables declaration - do not modify
	private javax.swing.JButton aniadirButton;
	private javax.swing.JComboBox mesBox;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JSpinner diaSpinner;
	private javax.swing.JSpinner anioSpinner;
	private javax.swing.JTextField nombreText;
	private javax.swing.JTextField apellido1Text;
	private javax.swing.JTextField apellido2Text;
	private javax.swing.JTextField telefonoText;
	private javax.swing.JTextField dniText;
	private javax.swing.JTextField emailText;
	// End of variables declaration
}
