package vista;

import java.awt.Toolkit;

import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

public class VistaConsultas extends javax.swing.JFrame {

    /**
     * Creates new form VistaConsultas
     */
    public VistaConsultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. 	
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		this.setIconImage(Toolkit.getDefaultToolkit().getImage(".\\media\\LOGO.png"));
		setLocationRelativeTo(null);
		setResizable(false);
		setTitle("RentLeon Consultas");
		setSize(244, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                    

    public void setText(String text) {
    	this.text.setHorizontalAlignment(SwingConstants.CENTER);
    	this.text.setVerticalAlignment(SwingConstants.CENTER);
    	this.text.setText(text);
    }
    
    public void mostrarError() {
    	JOptionPane.showMessageDialog(null, "No se puedo realizar la consultar", "Error Consulta", JOptionPane.ERROR_MESSAGE);
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JLabel text;
    // End of variables declaration                   
}
