package vista;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.ActionListener;
import java.sql.Date;
import java.util.Calendar;

import javax.swing.JOptionPane;

import implementacion.AlquilerDao;

/**
 *
 * @author rauls
 */
public class VistaAlquiler extends javax.swing.JFrame {

	/**
	 * Creates new form VistaAniadirAlquiler
	 */
	public VistaAlquiler() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		dniText = new javax.swing.JTextField();
		mesInicioBox = new javax.swing.JComboBox();
		mesFinalBox = new javax.swing.JComboBox();
		vehiculosDisponiblesBox = new javax.swing.JComboBox();
		jLabel2 = new javax.swing.JLabel();
		diaFinalSpinner = new javax.swing.JSpinner();
		anioFinalSpinner = new javax.swing.JSpinner();
		anioInicioSpinner = new javax.swing.JSpinner();
		diaInicioSpinner = new javax.swing.JSpinner();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		aniadirButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("DNI");

		mesInicioBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril",
				"Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

		mesFinalBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril",
				"Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

		jLabel2.setText("Vehiculo");

		jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel3.setText("Fecha Inicio");

		jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel4.setText("Fecha Fin");

		aniadirButton.setText("Añadir");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(45, 45, 45)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel3)
						.addGroup(layout.createSequentialGroup()
								.addComponent(diaInicioSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(mesInicioBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabel2).addComponent(jLabel1))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(
												dniText, javax.swing.GroupLayout.PREFERRED_SIZE, 105,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(vehiculosDisponiblesBox, javax.swing.GroupLayout.PREFERRED_SIZE,
												105, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabel4)
										.addGroup(layout.createSequentialGroup()
												.addComponent(anioInicioSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
														84, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(44, 44, 44)
												.addComponent(diaFinalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(mesFinalBox, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(anioFinalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 84,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addGap(32, 32, 32))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(aniadirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(228, 228, 228)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(26, 26, 26)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(dniText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(vehiculosDisponiblesBox, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(jLabel4))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(mesInicioBox, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(mesFinalBox, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(diaFinalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(anioFinalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(anioInicioSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(diaInicioSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(32, 32, 32).addComponent(aniadirButton).addContainerGap()));

		pack();
	}// </editor-fold>

	public void listenerAniadirButton(ActionListener listenForButtons) {
		this.aniadirButton.setText("Añadir");
		this.aniadirButton.addActionListener(listenForButtons);
	}

	public void listenerModificarButton(ActionListener listenForButtons) {
		this.aniadirButton.setText("Modificar");
		this.aniadirButton.addActionListener(listenForButtons);
	}

	public void avisarAlquilerAniadidoCorrecto() {
		JOptionPane.showMessageDialog(null, "Alquiler añadido correctamente", null, JOptionPane.INFORMATION_MESSAGE,
				null);
	}
	
	public void avisarAlquilerModificadoCorrecto() {
		JOptionPane.showMessageDialog(null, "Alquiler añadido correctamente", null, JOptionPane.INFORMATION_MESSAGE,
				null);
	}

	public String mostrarVentanaFinalizarAlquiler() {
		String id = JOptionPane.showInputDialog(null, "Introduce el ID:", "Finalizar Alquiler",
				JOptionPane.QUESTION_MESSAGE);
		return id;
	}
	
	public String mostrarVentanaConsultarAlquiler() {
		String id = JOptionPane.showInputDialog(null, "Introduce el ID:", "Consultar Alquiler",
				JOptionPane.QUESTION_MESSAGE);
		return id;
	}

	public Date getFechaInicio() {
		Calendar cal = Calendar.getInstance();
		cal.set(Calendar.YEAR, Integer.valueOf(anioInicioSpinner.getValue().toString()));
		cal.set(Calendar.MONTH, mesInicioBox.getSelectedIndex());
		cal.set(Calendar.DAY_OF_MONTH, Integer.valueOf(diaInicioSpinner.getValue().toString()));
		return new Date(cal.getTimeInMillis());
	}

	public Date getFechaFin() {
		Calendar cal = Calendar.getInstance();
		cal.set(Calendar.YEAR, Integer.valueOf(anioFinalSpinner.getValue().toString()));
		cal.set(Calendar.MONTH, mesFinalBox.getSelectedIndex());
		cal.set(Calendar.DAY_OF_MONTH, Integer.valueOf(diaFinalSpinner.getValue().toString()));
		return new Date(cal.getTimeInMillis());
	}

	public String getDNIText() {
		return dniText.getText();
	}

	public String getVehiculo() {
		return vehiculosDisponiblesBox.getSelectedItem().toString();
	}

	public void setVehiculosDisponiblesBox(String vehiculo) {
		// TODO
		// this.vehiculosDisponiblesBox = vehiculosDisponiblesBox;
	}

	public void setDniText(String dni) {
		this.dniText.setText(dni);
	}

	public void setInicioDate(Date fecha) {
		Calendar cal = Calendar.getInstance();
		cal.setTime(fecha);
		this.diaInicioSpinner.setValue(cal.get(Calendar.DAY_OF_MONTH));
		this.mesInicioBox.setSelectedIndex(cal.get(Calendar.MONTH));
		this.anioInicioSpinner.setValue(cal.get(Calendar.YEAR));
	}

	public void setFinalDate(Date fecha) {
		Calendar cal = Calendar.getInstance();
		cal.setTime(fecha);
		this.diaFinalSpinner.setValue(cal.get(Calendar.DAY_OF_MONTH));
		this.mesFinalBox.setSelectedIndex(cal.get(Calendar.MONTH));
		this.anioFinalSpinner.setValue(cal.get(Calendar.YEAR));
	}

	// Variables declaration - do not modify
	private javax.swing.JButton aniadirButton;
	private javax.swing.JComboBox mesInicioBox;
	private javax.swing.JComboBox mesFinalBox;
	private javax.swing.JComboBox vehiculosDisponiblesBox;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JSpinner diaFinalSpinner;
	private javax.swing.JSpinner anioFinalSpinner;
	private javax.swing.JSpinner anioInicioSpinner;
	private javax.swing.JSpinner diaInicioSpinner;
	private javax.swing.JTextField dniText;
	// End of variables declaration
}
