package vista;

import javax.swing.SpinnerNumberModel;

import implementacion.VehiculoImpl;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rauls
 */
public class VistaAniadirVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form VistaAniadirVehiculo
     */
    public VistaAniadirVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        plazasBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        combustibleBox = new javax.swing.JComboBox();
        matriculaText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        aniadirButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        costeSpinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        tipoBox = new javax.swing.JComboBox();
        
        this.setTitle("Añadir Vehiculo RentLeon");
        this.setSize(510, 167);
        this.setLocationRelativeTo(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Plazas");

        plazasBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "7", "9" }));

        jLabel2.setText("Combustible");

        combustibleBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diesel", "Gasolina", "Electrico", "Hibrido" }));

        jLabel3.setText("Matricula");

        aniadirButton.setText("Validar");
        aniadirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aniadirButtonClicked(evt);
            }
        });

        jLabel4.setText("Coste");

        costeSpinner.setToolTipText("");
        costeSpinner.setOpaque(false);
        costeSpinner.setVerifyInputWhenFocusTarget(false);
        costeSpinner.setFocusable(false);
        SpinnerNumberModel spinModel = new SpinnerNumberModel();
        spinModel.setMinimum(0);
        spinModel.setStepSize(100);
        costeSpinner.setModel(spinModel);
        
        jLabel5.setText("Tipo");

        tipoBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Turismo", "Furgoneta", "Caravana" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(combustibleBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(plazasBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(167, 167, 167)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(matriculaText)
                                    .addComponent(costeSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                            .addComponent(tipoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(aniadirButton)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plazasBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(costeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(combustibleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matriculaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tipoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(aniadirButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void aniadirButtonClicked(java.awt.event.ActionEvent evt) {                                           
    	// TODO implementar modelo
    	VehiculoImpl a = new VehiculoImpl();
    	a.aniadirVehiculo(matriculaText.getText(), tipoBox.getSelectedItem().toString(), Integer.valueOf(plazasBox.getSelectedItem().toString()), combustibleBox.getSelectedItem().toString(), (int) costeSpinner.getValue());
    }                                                                                    

    // Variables declaration - do not modify                     
    private javax.swing.JButton aniadirButton;
    private javax.swing.JComboBox plazasBox;
    private javax.swing.JComboBox combustibleBox;
    private javax.swing.JComboBox tipoBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner costeSpinner;
    private javax.swing.JTextField matriculaText;
    // End of variables declaration               
}
